### ISSUE TITLE
Final Push

### ISSUE THREAD

**Issue by ozkriff** [ozkriff/zemeroth#580]
I had a break from Zemeroth for a few months but it didn't really help - still tired of this protracted project. I don't want to abandon yet another unfinished game, so the plan is to force myself to complete a minimal two-release roadmap and declare the game kinda finished.

To consider Zemeroth "done" I should:

- 0.7
  - [ ] GitHub updates
    - [x] Create a "Final Push" meta issue
    - [ ] readme: clearly define the project's scope
    - [ ] clean up out-of-scope GitHub issues
    - [ ] readme: update the roadmap section
  - [ ] Merge all assets into the main repo, update docs and CI scripts (TODO: issue?)
  - [ ] Summoned imps should be white colored for a few frames (#534)
  - [ ] Make buttons in main menu similary-sized (TODO: issue?)
    - [ ] aligh info buttons in the campaign menu and the abilitirs panel
  - [ ] Sounds (#221)
  - [ ] Background Music: wind & slow drums (#60)
    - [ ] (optional) More calm music for menu screens
  - [ ] release v0.7 + text&video devlogs
- 0.8
  - [ ] Click outside of the map should cancel ability/selection too (TODO: issue?)
  - [ ] Remove ability parameters (TODO: find issue)
  - [ ] BombPush should push away other bombs #532
  - [ ] Add at least four new enemies (TODO: issue!)
    - [ ] tweak current enemies to match the new onces
  - [ ] Add 4 Intermediate bosses for two campaign battles
  - [ ] Add Zemeroth as a final boss
  - [ ] Add at lest six new agent types/upgrades
  - [ ] New campaign structure with 6 normal fights and 3 bosses (TODO: issue)
  - [ ] A few lore text messages in the key points of the campaign
  - [ ] demo battles menu screen (TODO: issue?)
  - [ ] readme: detailed overview of all game stuff (with gifs) (TODO: issue)
  - [ ] Android (#258)
    - [ ] google play? (optional)
  - [ ] release v0.8 + text&video devlogs
- Past 0.8
  - [ ] text and video retrospective of the whole project
    - [ ] post Russian translation to habr

I might also decide to add a few small tasks in the process, we'll see.

The main idea behind this final push is to ignore all tech debt and focus only on tasks that aren't that hard to implement but will result in a user-visible changes. Hope that will compensate my terrible self-discipline)

**Comment by ozkriff** [comment]
Well, it feels more like a "final crawl" 🐌 in practice but I'm still moving through the roadmap, so the game will be finished someday I guess. :)
